/*******************************************************************************
 * Copyright (c) 2010, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @header      functions.h
 * @copyright   eosgarden 2010 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    Program's constants
 */

#ifndef _HEXPRINT_FUNCTIONS_H_
#define _HEXPRINT_FUNCTIONS_H_
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/*!
 * @function    hexprint_display
 * @abstract    Displays a file as an hexadecimal dump
 * @param       fp      A pointer to the file to display
 * @param       cols    The number of hexadecimal columns to display
 * @param       ascii   Whether to display ASCII data or not
 * @param       lines   Whether to display the line numbers or not
 * @result      void
 */
void hexprint_display( FILE * fp, unsigned int cols, bool ascii, bool lines );

/*!
 * @function    hexprint_display_hex
 * @abstract    Displays data as hexadecimal data
 * @param       buffer  The data to display
 * @param       length  The length of the data to display
 * @param       cols    The number of data columns to display
 * @result      void
 */
void hexprint_display_hex( char * buffer, unsigned int length, unsigned int cols );

/*!
 * @function    hexprint_display_ascii
 * @abstract    Displays data as ASCII data
 * @param       buffer  The data to display
 * @param       length  The length of the data to display
 * @param       cols    The number of data columns to display
 * @result      void
 */
void hexprint_display_ascii( char * buffer, unsigned int length, unsigned int cols );

/*!
 * @function    hexprint_get_cli_args
 * @abstract    Processes the command line parameters passed to this program
 * @param       argc    The number of command line arguments
 * @param       argv    A pointer to the command line arguments
 * @param       args    A pointer to the structure in which to store the arguments values
 * @result      void
 */
void hexprint_get_cli_args( int argc, char ** argv, hexprint_cli_args * args );

/*!
 * @function    hexprint_print_version
 * @abstract    
 * @result      void
 */
void hexprint_print_version( void );

/*!
 * @function    hexprint_print_help
 * @abstract    Prints the program's help dialog
 * @param       name    The program's executable name
 * @result      void
 */
void hexprint_print_help( char * name );

/*!
 * @function    hexprint_print_license
 * @abstract    Prints the program's license terms
 * @result      void
 */
void hexprint_print_license( void );

#ifdef __cplusplus
}
#endif

#endif /* _HEXPRINT_FUNCTIONS_H_ */
