/*******************************************************************************
 * Copyright (c) 2010, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @header      types.h
 * @copyright   eosgarden 2010 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    Program's type definitions
 */

#ifndef _HEXPRINT_TYPES_H_
#define _HEXPRINT_TYPES_H_
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/*! Defines the bool data type if not available (below ISO-C99) */
#ifndef __bool_true_false_are_defined
    #define bool                            _Bool
    #define true                            1
    #define false                           0
    #define __bool_true_false_are_defined   1
#endif

/*!
 * @typedef     hexprint_cli_args
 * @abstract    Structure representing the program's possible command line arguments
 * @field       version     Prints the program's version number
 * @field       license     Prints the program's license terms
 * @field       help        Prints the program's help screen
 * @field       cols        Number of hexadecimal columns to show
 * @field       group       Groups bytes
 * @field       ascii       Displays the ASCII data
 * @field       lines       Displays the lines numbers
 * @field       file        The path to the file to display
 */
typedef struct _hexprint_cli_args
{
    bool         version;
    bool         license;
    bool         help;
    unsigned int cols;
    unsigned int group;
    bool         ascii;
    bool         lines;
    char       * file;
}
hexprint_cli_args;

#ifdef __cplusplus
}
#endif

#endif /* _HEXPRINT_TYPES_H_ */

