/*******************************************************************************
 * Copyright (c) 2010, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        functions.c
 * @copyright   eosgarden 2010 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    Program's functions
 */

/* Local includes */
#include "hexprint.h"

/*!
 * @function    hexprint_display
 * @abstract    Displays a file as an hexadecimal dump
 * @param       fp      A pointer to the file to display
 * @param       cols    The number of hexadecimal columns to display
 * @param       ascii   Whether to display ASCII data or not
 * @param       lines   Whether to display the line numbers or not
 * @result      void
 */
void hexprint_display( FILE * fp, unsigned int cols, bool ascii, bool lines )
{
    char       * buffer;
    unsigned int length;
    unsigned int offset;
    
    length = 0;
    offset = 0;
    
    if( NULL == ( buffer = ( char * )malloc( sizeof( char ) * cols ) ) )
    {
        printf( "Error: not enough memory" );
        fclose( fp );
        exit( EXIT_FAILURE );
    }
    
    while( ( length = fread( buffer, sizeof( char ), cols, fp ) ) > 0 )
    {
        if( lines == true )
        {
            printf( "%010d: ", offset );
        }
        
        offset += cols;
        
        hexprint_display_hex( buffer, length, cols );
        
        if( ascii == true )
        {
            printf( " | " );
            hexprint_display_ascii( buffer, length, cols );
        }
        
        printf( "\n" );
    }
    
    free( buffer );
}

/*!
 * @function    hexprint_display_hex
 * @abstract    Displays data as hexadecimal data
 * @param       buffer  The data to display
 * @param       length  The length of the data to display
 * @param       cols    The number of data columns to display
 * @result      void
 */
void hexprint_display_hex( char * buffer, unsigned int length, unsigned int cols )
{
    unsigned int i;
    
    for( i = 0; i < cols; i++ )
    {
        if( i < length )
        {
            printf( "%02X", ( unsigned char )buffer[ i ] );
        }
        else
        {
            printf( "  " );
        }
        
        if( i < cols - 1 )
        {
            printf( " " );
        }
    }
}

/*!
 * @function    hexprint_display_ascii
 * @abstract    Displays data as ASCII data
 * @param       buffer  The data to display
 * @param       length  The length of the data to display
 * @param       cols    The number of data columns to display
 * @result      void
 */
void hexprint_display_ascii( char * buffer, unsigned int length, unsigned int cols )
{
    unsigned int i;
    char         c;
    
    for( i = 0; i < cols; i++ )
    {
        c = 0;
        
        if( i < length )
        {
            c = buffer[ i ];
            
            if( ( ( ( c & 0x80 ) == 0 ) && isprint( ( int )c ) ) )
            {
                printf( "%c", c );
            }
            else
            {
                printf( "." );
            }
        }
    }
}

/*!
 * @function    hexprint_get_cli_args
 * @abstract    Processes the command line parameters passed to this program
 * @param       argc    The number of command line arguments
 * @param       argv    A pointer to the command line arguments
 * @param       args    A pointer to the structure in which to store the arguments values
 * @result      void
 */
void hexprint_get_cli_args( int argc, char ** argv, hexprint_cli_args * args )
{
    int    i;
    char * option;
    
    args->version = false;
    args->help    = false;
    args->cols    = HEXPRINT_DEFAULT_COLS;
    args->ascii   = HEXPRINT_DEFAULT_ASCII;
    args->lines   = HEXPRINT_DEFAULT_LINES;
    args->file    = NULL;
    
    i = 0;
    
    while( ++i < argc && ( ( char * )*( ++argv ) )[ 0 ] == '-' )
    {
        switch( ( ( char * )*( argv ) )[ 1 ] )
        {
            case 'a': args->ascii   = false;    break;
            case 'n': args->lines   = false;    break;
            case 'v': args->version = true;     break;
            case 'h': args->help    = true;     break;
            case 'l': args->license = true;     break;
            case 'c':
                
                if( i < argc - 1 )
                {
                    args->cols = atoi( *( ++argv ) );
                }
                break;
            
            case '-':
                
                option = *( argv ) + 1;
                
                if( strcmp( option, "no-ascii" ) == 0 )
                {
                    args->ascii = false;
                }
                if( strcmp( option, "columns" ) == 0 )
                {
                    if( i < argc - 1 )
                    {
                        args->cols = atoi( *( ++argv ) );
                    }
                }
                else if( strcmp( option, "no-lines" ) == 0 )
                {
                    args->lines = false;
                }
                else if( strcmp( option, "version" ) == 0 )
                {
                    args->version = true;
                }
                else if( strcmp( option, "help" ) == 0 )
                {
                    args->help = true;
                }
                else if( strcmp( option, "license" ) == 0 )
                {
                    args->help = true;
                }
                
            default:
                
                break;
        }
    }
    
    if( i++ < argc )
    {
        args->file = *( argv );
    }
}

/*!
 * @function    hexprint_print_version
 * @abstract    
 * @result      void
 */
void hexprint_print_version( void )
{
    printf( "Version: %s\n", HEXPRINT_VERSION );
}

/*!
 * @function    hexprint_print_help
 * @abstract    Prints the program's help dialog
 * @param       name    The program's executable name
 * @result      void
 */
void hexprint_print_help( char * name )
{
    printf
    (
        "\n"
        "HexPrint (%s)\n"
        "Displays a file's content as an hexadecimal dump.\n"
        "\n"
        "Copyright (c) 2010, Jean-David Gadina <macmade@eosgarden.com>\n"
        "Distributed under the Boost Software License, Version 1.0.\n"
        "\n"
        "Usage: %s [OPTIONS] [FILE]\n"
        "\n"
        "Options:\n"
        "    \n"
        "    -c [i] | --columns [i]\n"
        "    The number of columns to display for the hexadecimal code (integer value)\n"
        "    \n"
        "    -a | --no-ascii\n"
        "    Do not display the ASCII code\n"
        "    \n"
        "    -n | --no-lines\n"
        "    Do not display the lines numbers\n"
        "    \n"
        "    -h | --help\n"
        "    Print this help message\n"
        "    \n"
        "    -v | --version\n"
        "    Print the version number\n"
        "    \n"
        "    -l | --license\n"
        "    Print the license terms\n"
        "\n",
        HEXPRINT_VERSION,
        name
    );
}

/*!
 * @function    hexprint_print_license
 * @abstract    Prints the program's license terms
 * @result      void
 */
void hexprint_print_license( void )
{
    printf
    (
        "\n"
        "Boost Software License - Version 1.0 - August 17th, 2003\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person or organization\n"
        "obtaining a copy of the software and accompanying documentation covered by\n"
        "this license (the \"Software\") to use, reproduce, display, distribute,\n"
        "execute, and transmit the Software, and to prepare derivative works of the\n"
        "Software, and to permit third-parties to whom the Software is furnished to\n"
        "do so, all subject to the following:\n"
        "\n"
        "The copyright notices in the Software and this entire statement, including\n"
        "the above license grant, this restriction and the following disclaimer,\n"
        "must be included in all copies of the Software, in whole or in part, and\n"
        "all derivative works of the Software, unless such copies or derivative\n"
        "works are solely in the form of machine-executable object code generated by\n"
        "a source language processor.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT\n"
        "SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE\n"
        "FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,\n"
        "ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\n"
        "DEALINGS IN THE SOFTWARE.\n"
        "\n"
    );
}
